# Generated by Django 5.1.3 on 2024-11-14 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme_sysoev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='askme_sysoev.question'),
            preserve_default=False,
        ),
    ]
