# Generated by Django 5.1.3 on 2024-11-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme_sysoev', '0002_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
