# Generated by Django 5.1.3 on 2024-11-14 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme_sysoev', '0003_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontag',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questiontag', to='askme_sysoev.question'),
        ),
    ]
